letsseenow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -56,7 +56,7 @@ jobs:
       env:
        TF_IN_AUTOMATION: true
        TF_INPUT: false
-       TF_WORKING_DIR: Policy-Assignment/**/*
+   #   TF_WORKING_DIR: Policy-Assignment/**/*
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
@@ -74,31 +74,44 @@ jobs:
         - name: Setup Terraform
           uses: hashicorp/setup-terraform@v1
       
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
-        - name: Terraform Init
-          run: terraform init
-          working-directory: ${{ env.TF_WORKING_DIR }}
 
-    # Checks that all Terraform configuration files adhere to a canonical format
-        - name: Terraform Format
-          run: terraform fmt -check
+        - name: Find configuration files
+          run: |
+            find Policy-Assignment -name "*.tf"
+            find Policy-Assignment -name "*.json"
+          id: find_files
+        - name: Deploy policies
+          run: |
+            terraform init
+            terraform validate
+            terraform plan -var-file=variables.tfvars -out=tfplan -input=false -no-color
+            terraform apply -input=false -auto-approve
+          if: steps.find_files.outputs.stdout != ''
+    # # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    #     - name: Terraform Init
+    #       run: terraform init
+    #       working-directory: ${{ env.TF_WORKING_DIR }}
+
+    # # Checks that all Terraform configuration files adhere to a canonical format
+    #     - name: Terraform Format
+    #       run: terraform fmt -check
     
-    # Checks that all Terraform configuration files adhere to a canonical format
+    # # Checks that all Terraform configuration files adhere to a canonical format
     
-        - name: Terraform Validate
-          run: terraform validate -no-color
+    #     - name: Terraform Validate
+    #       run: terraform validate -no-color
 
-    # Generates an execution plan for Terraform
-        - name: Terraform Plan
-          run: terraform plan
-          continue-on-error: true
+    # # Generates an execution plan for Terraform
+    #     - name: Terraform Plan
+    #       run: terraform plan
+    #       continue-on-error: true
 
 
-        - name: Terraform Plan Status
-          if: steps.plan.outcome == 'failure'
-          run: exit 1
+    #     - name: Terraform Plan Status
+    #       if: steps.plan.outcome == 'failure'
+    #       run: exit 1
     
-        - name: Terraform Apply
-          if: ${{ success() }}
-          run: terraform apply -auto-approve
+    #     - name: Terraform Apply
+    #       if: ${{ success() }}
+    #       run: terraform apply -auto-approve
           
